"""
Django settings for littlelemon project.

<<<<<<< HEAD
Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
=======
Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
>>>>>>> 8ab6f7f157ca9c8ce9f6d96e5e8891cd544e82f6
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
<<<<<<< HEAD
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qoh((w3)ltuyt@(p#qsl9m-v5zqig3ql^*o=rd$q#f*6ldszsh'
=======
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5_i&*+9k97^2t8gq@ldl=qql(j7djemhawm((at1r+wdwzyq7('
>>>>>>> 8ab6f7f157ca9c8ce9f6d96e5e8891cd544e82f6

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'littlelemon.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'littlelemon.wsgi.application'


# Database
<<<<<<< HEAD
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases
=======
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
>>>>>>> 8ab6f7f157ca9c8ce9f6d96e5e8891cd544e82f6

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
<<<<<<< HEAD
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators
=======
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
>>>>>>> 8ab6f7f157ca9c8ce9f6d96e5e8891cd544e82f6

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
<<<<<<< HEAD
# https://docs.djangoproject.com/en/4.0/topics/i18n/
=======
# https://docs.djangoproject.com/en/4.2/topics/i18n/
>>>>>>> 8ab6f7f157ca9c8ce9f6d96e5e8891cd544e82f6

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
<<<<<<< HEAD
# https://docs.djangoproject.com/en/4.0/howto/static-files/
=======
# https://docs.djangoproject.com/en/4.2/howto/static-files/
>>>>>>> 8ab6f7f157ca9c8ce9f6d96e5e8891cd544e82f6

STATIC_URL = 'static/'

# Default primary key field type
<<<<<<< HEAD
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field
=======
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
>>>>>>> 8ab6f7f157ca9c8ce9f6d96e5e8891cd544e82f6

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
