# Generated by Django 4.2.7 on 2023-11-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='no_of_guests',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='menu',
            name='inventory',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
